### PR TITLE
Refactor pdfviewerwindow.ui

### PR DESCRIPTION
**Pull request by dannyedel**
Because of the problems on MacOS #74 I want to switch the current palette-based colors for stylesheet-based colors.

### CODE REVIEW

**Comment by dannyedel** [comment]
@wwwdata can you check whether building this PR results in a window *with* a wallclock (bottom left) and a presentation clock (bottom right)? The window background should be grey-ish (or whatever your system's default colors are)

If this works (this would confirm the clocks indeed work correctly and the fonts get rendered) I will add another commit to specify a stylesheet.

**Comment by wwwdata** [comment]
wow! finally it works without a flaw on my mac. It even correctly resizes on my main and laptop screen in fullsize. Very nice pr :) :shipit: 

screen shot 2015-10-02 at 12 26 40

**Comment by dannyedel** [comment]
@wwwdata can you check whether it now works fully as intended (white text, black background, some numbers) on macos?

**Comment by wwwdata** [comment]
ok, looks like this now: 

screen shot 2015-10-07 at 13 09 38

**Comment by dannyedel** [comment]
Allright, that's much how it's supposed to look as of now. I'll check a couple of example pdfs and then merge.

**Comment by dannyedel** [comment]
@wwwdata my testing showed that at 35ddf98, PDF hyperlinks got rendered as black boxes (instead of transparent) and the "goto" dialog (G button) was white-on-black aswell (not intended).

Can you check this is also present in MacOS, and gone in dbad741? (if necessary, `touch pdfviewerwindow.h` to enforce recompilation of the `pdfviewerwindow.cpp` file or make clean/make)

If you give your final ok, I'll merge.

**Comment by wwwdata** [comment]
I included the `hyperref` package in the rectangle sample pdf and inserted a link with `\url{}`. Seems to work fine, see my screnshot:

screen shot 2015-10-08 at 10 42 22

**Comment by dannyedel** [comment]
Sorry, but `dspdfviewer` doesn't render hyperlink types other than `goto` yet (I should have maybe been more specific), so this doesn't really count.

Please try the lipsum.pdf from https://github.com/dannyedel/example-beamer-presentations/releases, it should contain the little "advance one page / back one page" links on the audience screen. (If you do not see black boxes when compiling the 35ddf98, that would also be interesting...)

**Comment by wwwdata** [comment]
yes, it contains these links and they are working. But they were also contained in the colored box as you see in the screenshot. So this means it's working, right?

screen shot 2015-10-08 at 10 50 52

**Comment by dannyedel** [comment]
The colored-rectangles only has one page, so it probably doesn't contain any hyperlink areas (only the graphics), but if lipsum works aswell that should be a definite.

I'll merge it into master, maybe you can look at #80 : )

**Pull request merged**
