### PR TITLE
Migrate to current Qt and Poppler libraries

### PR DESCRIPTION
**Pull request by dannyedel**
Try to compile with Qt5 / poppler-qt5 bindings and see how much problems actually arise, since [poppler-qt5] is "currently in development" (already used by Okular, and included since debian jessie and ubuntu trusty) and [Qt5] is already declared stable.

If this *basically* works, try to adapt the CMakeLists.txt to allow compilation in both a qt4 and a qt5 environment.

* Implement this with a cmake-time switch.
  * Bonus points: Default to auto-detection (if both qt5 and poppler-qt5 are available, switch to the qt5 mode)
  * Allows packagers to define the option to enforce a predictable run-time dependency (binary-based distributions) or leave it at the default value (source-based distributions)

[poppler-qt5]: http://people.freedesktop.org/~aacid/docs/qt5/
[Qt5]: http://doc.qt.io/

### CODE REVIEW

**Comment by dannyedel** [comment]
This commit enables building with qt5, but leaving the default at qt4. To build with qt5, call:

cmake -DUseQtFive=ON /path/to/source
make

Please note that this is considered experimental for now.

Still left to do: Backport libpoppler-qt5-dev to precise in order to allow travis (running on precise) to test compiling there. Until then the PR will not be merged.

**Comment by dannyedel** [comment]
Current status:

* The code "basically" compiles with qt5.
* I have backported poppler-qt5 from trusty LTS to precise LTS, see 
  https://launchpad.net/~dannyedel/+archive/ubuntu/libpoppler-qt5-backports
* travis uses this to verify building against qt5
* travis has been 1up'd to a build matrix testing the various supported compiling techniques
  * Using debuild, qt as specified in d/rules
  * Using cmake from a git clone, qt4
  * Using cmake from a git clone, qt5
  * Using cmake from a tarball, no qt specified
* Right now, clang+qt5 fails.
  * This is likely due a bug in qt5, but right now I don't care about backporting entire qt5 to precise. Maybe soon™.

**Comment by projekter** [comment]
I managed to compile dspdfviewer itself with Qt5 and the most recent versions of all dependencies (e.g. poppler 0.36.0, which just came out three days ago) on Windows and provided a [release](https://github.com/projekter/dspdfviewer/releases/tag/v1.13-212-gf44b598).
It was also possible to build a debug version of all those which now works, in contrast to the Qt4 debug version (I can upload it as well if desired).

**Comment by dannyedel** [comment]
Thanks again, I see it now has a `setup.exe` with progress bars and requiring me to click next a couple of times, really really cool!

<sarcasm>All that is missing is a 10-meter-long EULA you have to sign over your soul with and a 500MB RAM Auto-Updater, then its perfect ^^</sarcasm>

No seriously, it is great. Has an uninstaller, start menu entry, help file and offers Desktop shortcut. Wouldn't know what to improve there.

It is linked on the [windows installation] website section now, since that links to your `/releases/` page directly which lists the Qt5 Release at the top, so I hope users will find it. Feel free to update and improve the [source] to advertise that a bit.

I will try this out once I'm at a real windows machine again (I scrapped my last one and use wine for the occasional win32 program). Under wine, it installs and runs nicely. Even the uninstaller works perfect.

Did you have any win32-specific problems and/or need `#ifdef MSVC_COMPILER_STUFF` style source file changes that I should take upstream? If so, please pullrequest these as fresh small branches off my `master` and I'll merge them in.

[windows installation]: http://dspdfviewer.danny-edel.de/installation/windows.html
[source]: https://github.com/dannyedel/dspdfviewer/blob/gh-pages/installation/windows.md

**Comment by projekter** [comment]
I created a [pull request](https://github.com/dannyedel/dspdfviewer/pull/76) for those specific changes. One of them was not related to Qt5 but I think to a Visual C++ non-support, the other one includes the Qt5 Windows plugin - maybe something similar is required for other OS's.
As you encouraged me to do my own changes to the source, I also included a fix of [https://github.com/dannyedel/dspdfviewer/issues/58](presentation/notes at the same screen). I did not make a release out of it, I will for integration in the main project.
I also discovered that DSPDFViewer::renderForTarget is not used anywhere and removed this function.

**Pull request merged**
