### PR TITLE
=Added Windows binaries.

### PR DESCRIPTION
**Pull request by projekter**
Included description of compilation in README.md.
Included Windows binaries.

Made some adjustments to certains files in order to compile with VC++ 2010.
I think these adjustments should not be merged; they are specific to VC++ 2010 and will most likely drop compatibility with other compilers [for( : ) loops are called for each( in )]. Furthermore, I had to changed "enum class" to "enum" and remove a deleted constructor, as those features are not supported by VC++ 2010.

### CODE REVIEW

**Comment by dannyedel** [comment]
Wow :thumbsup: for doing this!

Thanks for putting all that work together, it seems compiling under windows is no small task at all. But you're right, commiting it like this won't work (especially because now it doesn't build anymore on travis' compilers). Let's see if we can find a way to get "one sourcecode that compiles even on windows" working.

First things first: Please *separate the compilation results (binaries) from the sourcecode*. If I understand it correctly, that's exactly what github's [releases] feature is for.
For example, it should allow you to drop binaries to the [v1.12] release *in your fork* (there'll be a "Edit tag" icon allowing you to add binaries created from that version). That also makes it painless to remember what version you compiled something from, simply *create your own tags* and then post binaries to them if you compile from a revision that doesn't have a tag from me already.

Please make a fresh branch off my master for this, since otherwise git would simply save one "add loads of binaries" commit and then another "remove loads of binaries".

I'd recommend working in "feature branches" anyway, they're easier to throw away, merge or force-push.

Once you've got a pure sourcecode branch, we can try to "box in" windows-specific changes with a little help of those - often brain-twisting - preprocessor `#if`s. Stackoverflow has a nice example on [ifdef visual studio].

So maybe, if you can get code like the following to work:

```cpp
#if _MSC_VER == 1600
// do weird stuff for MS Visual C++ 2010
#else
// my original code
#endif
```

Then I can completely integrate your source-level changes to the main codebase, while not affecting anyone using any compiler other than MSVC2010.

On the other hand, you might want to consider upgrading to a more recent version (not just for my project). According to Microsoft's own c++11 [feature list], their more recent compilers implement a lot more of c++11, and I'd expect you'll run into more and more problems since other compilers have them for a while and programmers (not just me) will start using the new constructs.

[releases]: https://help.github.com/articles/creating-releases/
[v1.12]: https://github.com/projekter/dspdfviewer/releases/tag/v1.12
[ifdef visual studio]: http://stackoverflow.com/a/3786113
[feature list]: https://msdn.microsoft.com/en-us/library/hh567368.aspx#featurelist

**Comment by projekter** [comment]
This should be possible. The only reason why I used VC++ 2010 (I have never worked with C++ before and had to install everything from the scratch) is that I read in your readme that you made use of Qt 4. The most recent version of Qt 4 has builds for 2008 and 2010, so I chose 2010. If Qt 5 will work, I can install this and then use VC++ 2013 which hopefully supports more of the features.

**Comment by dannyedel** [comment]
Please give this a shot. If it works, it may make everything a lot easier : )

Under my linux systems, qt4 is supported even in the most recent distributions using the most recent compilers, so I didn't expect that to force anyone to use an old compiler.

**Comment by projekter** [comment]
I'll give it at try. This will take some time, as after installing I have to recompile all the libraries.

**Comment by dannyedel** [comment]
If you can't get pre-compiled releases for a more recent msvc compiler, you could give the instructions from http://doc.qt.io/qt-4.8/install-win.html a try. At least they don't say "will not work with current MSVC".

I think I remember why I chose qt4: The poppler (PDF decoder) binding did not exist (yet) for qt5, and it seems poppler-qt4 is for now still the safer choice:

Quote http://people.freedesktop.org/~aacid/docs/qt5/
> The Poppler Qt5 interface library is in developement.

Quote http://people.freedesktop.org/~aacid/docs/qt4/
> The Poppler Qt4 interface library is quite stable and working.

**Comment by projekter** [comment]
Compilation has finished. With VC2013, you do not need to change any of the files. It is a bit harder to compile poppler, but Qt4, boost and DS PDF itself all compiled without any problems.
I have created a new fork (which already includes the file open dialog) and created a release as you wished. I have tagged it [v1.13](https://github.com/projekter/dspdfviewer/releases/tag/v1.13). However, GIT won't let me create a pull request for this, as no files have changed and the binaries are included only in the release.

**Comment by dannyedel** [comment]
Wow, I never expected my software to work **without source changes** under win32. I'll sure give this a shot when I'm next near a windows machine : )

In the meantime, if you create tags from a commit I havn't named please use the format (lastrelease) plus something, like  `v1.12-56-g0a0cf4a` (simply call `git describe`, it will spit something out you can use straight away), so that if I name something v1.13 there won't be any confusion.

But hey, I'll probably just call this one v1.13 if there aren't any bugs noticeable on any of my systems. (just for the future, please leave incrementing version number to me)

If you could post the windows-specific installation instructions to [the windows.md page in the website][windows.md] that would be awesome. You should™ be able to click an edit icon straight on github, to spawn a pull-request automatically. Syntax is same as in the tickets here ([markdown]) plus a few [additions], like the comment tag, but I doubt you'll need these.

I expect the website to replace the "getting-lengthy" readme, especially for installation instructions. see #45 and feel free to add more : )

[windows.md]: https://github.com/dannyedel/dspdfviewer/blob/gh-pages/installation/windows.md
[markdown]: https://guides.github.com/features/mastering-markdown/
[additions]: http://jekyllrb.com/docs/templates/

--- snip ---

If you're happy with this, feel free to close/cancel the pull request afterwards.

**Comment by projekter** [comment]
Ok, I have added a sentence to the windows.md. Actually, there is not much installing, only extract and run. And to avoid confusion, I have renamed my release to v1.13-55-g3af1b8c.

**Comment by dannyedel** [comment]
Sorry for the noise, but I just *had* to share this : )

For your information, your windows-binary runs flawlessly **under wine.** (at least the [wine-development] version in debian). It is a lot slower, but considering its a few layers of emulation, I still think that's pretty cool.

[wine-development]: https://packages.debian.org/sid/wine-development

**Pull request closed without merging**
